### PR TITLE
Icon Changes

### PR DESCRIPTION
**Pull request by 233Neon**
- Added New Icon to PSP Minecraft made by me.
- Deleted the old one.

Why? Because who wants to look at a block when you can look at an actual Icon.

### CODE REVIEW

**Comment by IridescentRose** [comment]
Reasons for Rejection:
* Text is unreadable / difficult to read 
* Top of Logo is cut off prematurely
* End result is of poor quality
* Reasoning is far insufficient nor explains the need for this change
* Icon image contents are too small on the PSP

**Comment by 233Neon** [comment]
It's the exact resolution for the PSP. so either it's an issue with the
PSP, the PSP Image quality is too small, etc.

I'll try to fix these issues if you're ok with it. I just want to be
involved with this project one way or another and I don't like the current
Icon (Minecraft transparent dirt block / ICON0), It's just unprofessional.

Just wanted to help with the icon, so I'll try my best to fix these issues,
Thanks!




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
04/29/20,
06:41:03 PM

**Comment by MotoLegacy** [comment]
Buddy, look how small you choose to make the ICON0. That's not a PSP limitation, that's just bad graphic design. We already have new XMB images that'll be in the next few commits or so.

Your effort to try and contribute is appreciated, but we already have the XMB planned out.

Thanks!

**Comment by IridescentRose** [comment]
It's not an issue of the resolution, but the scaling itself. If you would like to contribute, look at Project-Raven and possibly submit work for internal data subsystems. That is the main focus to bring the project up to par with Java Edition. The ICON or look of the application on the XMB is not a concern in comparison to the content of the game itself.

**Comment by 233Neon** [comment]
): I legit looked up the resolution, but I guess I got false information.
It's not 'bad Graphic Design' first of all. (which is a super rude thing to
say).
I actually professionally worked as a graphic designer for big companies
for years, and now work as a Professional Game Developer. I just like
contributing to small GitHub projects I find online.


Please tell me what you think of this quick sample, and tell me if you'd
like anything changed.
I'm being as nice as possible here trying to contribute with the talent I
have to smaller people and projects for fun and to be as helpful as
possible.

Thanks.


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
04/29/20,
07:18:46 PM

**Comment by 233Neon** [comment]
I was originally working on the first Minecraft PSP game, I'm not sure what
happened to it really, I think they stopped working on it. But it was a fun
time and I did a lot for the project. I thought it was cool you were trying
to continue development (I was thinking about it myself) and I want to be
more involved in Minecraft remakes on other unsupported platforms.

You didn't have to be rude, I guess I get the gist you don't want me to
help with this project. I'll just go back to other projects or potentially
start my own Minecraft PSP version like I was thinking about before. :\
Just wanted to help. If I can help in any way please reach out to me.  I'm
just a nice dude and you didn't have to insult me since I got false
information from google. But it seems like you have 'everything figured
out' anyway... 😶😕



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
04/29/20,
07:26:44 PM

**Comment by MotoLegacy** [comment]
I wasn't trying to come out as rude, I'm just outlining that there is a difference between a hardware resolution limitation, and not scaling a simple image layer to appear larger and readable with said hardware resolution limitation. Please understand the difference. I will refrain from replying to this issue from this point, as it is closed and should remain silent.

**Comment by IridescentRose** [comment]
I do not speak for MotoLegacy and he is not a contributor to my project. I'm not being rude to you and simply said that the scaling is off and I have been provided with other assets.

**Comment by IridescentRose** [comment]
I also offered that if you wish to assist, you could help with the data side of things, and I would be glad to get some help as that is the main issue of the project.

**Comment by IridescentRose** [comment]
If you do want to go and do your own version, go ahead and do so as it is beneficial to the community regardless. I would not mind competition as basic economics shows that competition universally benefits the consumer (in this case the users) and creates more publicity for the scene.

**Comment by 233Neon** [comment]
It was kind of disrespectful for the amount of work I put into my
reputation as a game developer and a graphic designer to say I have poor
skill, I get what you're saying but it
did come out very rude. I will not reply to this any further as you're
obviously not interested in help. I have enough work as it is, and I'd
rather take in time for people who want/need the help and are going to be
grateful and appreciative for that time I dedicate for others.




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
04/29/20,
07:39:15 PM

**Comment by 233Neon** [comment]
And I like healthy competition as well. please don't take it as anything
personal against your project.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
04/29/20,
07:45:00 PM

**Comment by IridescentRose** [comment]
Alright. I'm done listening to this nonsense. Your issue is not with me, Iridescence, so I'm locking this as it's not my argument.

**Pull request closed without merging**
